services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always #always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ozang-app/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--databases", "16"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: ozang-app/Dockerfile
  #   container_name: o-zang-app
  #   restart: unless-stopped
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=password
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - ELASTICSEARCH_HOST=elastic
  #     - ELASTICSEARCH_PORT=9200


  #   ports:
  #     - "8082:80"
  #   depends_on:
  #     - db
  #     - redis
  #     - elastic

  elastic:
    build:
      context: .
      dockerfile: DockerfileEs
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - "5601:5601"
    depends_on:
      - elastic

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/bitnami/kafka

volumes:
  pgdata:
  redisdata:
  esdata:
  kafka-data:
