spring:
  application:
    name: sb01-otboo-team01
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      type_descriptor:
        sql_uuid: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG
    com.discodeit: debug

weather:
  api:
    key:  ${WEATHER_API_KEY}
    base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    nowcast:
      url: ${weather.api.base-url}/getUltraSrtNcst
    forecast:
      url: ${weather.api.base-url}/getVilageFst

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: https://dapi.kakao.com

batch:
  weather:
    retention-days: 1
  scheduler:
    weather-cleanup:
      enabled: false
    token-cleanup:
      enabled: false

#cloud:
#  aws:
#    credentials:
#      access-key: test-access-key
#      secret-key: test-secret-key
#    s3:
#      bucket: test-bucket
#      region: ap-northeast-2
#    region:
#      static: ap-northeast-2
#    stack:
#      auto: false
#
## 테스트용 파일 업로드 설정
#file:
#  upload:
#    clothes:
#      path: test/clothes/images/
#      allowed-extensions: jpg,jpeg,png,gif,webp
#      max-size: 10485760  # 10MB
#    profiles:
#      path: test/profiles/images/
#      allowed-extensions: jpg,jpeg,png,gif,webp
#      max-size: 10485760  # 10MB