spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5             # 유휴 연결 수 유지
      connection-timeout: 30000   # 연결 획득 타임아웃(30초)
      idle-timeout: 300000        # 유휴 연결 제거 시간(5분)
      max-lifetime: 1200000       # 연결 최대 수명(20분)
      leak-detection-threshold: 60000  # 연결 누수 감지(60초)

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 4
          max-idle: 4
          min-idle: 1

batch:
  weather:
    retention-days: 14
  scheduler:
    weather-cleanup:
      enabled: true
    token-cleanup:
      enabled: true
  job:
    enabled: false
  jdbc:
    initialize-schema: embedded

logging:
  level:
    root: WARN
    org.springframework.batch: WARN
    com.fourthread.ozang: INFO

cloud:
  aws:
    s3:
      bucket: ozang-prod-bucket

file:
  upload:
    clothes:
      path: prod/clothes/images/
      allowed-extensions: jpg,jpeg,png,gif,webp
      max-size: 5242880
    profiles:
      path: prod/profiles/images/
      allowed-extensions: jpg,jpeg,png,gif,webp
      max-size: 5242880

server:
  port: 80