spring:
  application:
    name: O-ZANG

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  batch:
    job:
      enabled: false
#    jdbc:
#      initialize-schema: never

logging:
  level:
    root: INFO
    com.fourthread.ozang: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

weather:
  api:
    key:  ${WEATHER_API_KEY}
    base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    nowcast:
      url: ${weather.api.base-url}/getUltraSrtNcst
    forecast:
      url: ${weather.api.base-url}/getVilageFst

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: https://dapi.kakao.com