spring:
  application:
    name: sb01-otboo-team01
  profiles:
    active: default # ???? ??
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        highlight_sql: true # SQL? ??? ?? ?? ??
        use_sql_comments: true
    open-in-view: false # OSIV ?

# ?? ?? ??
logging:
  level:
    root: info
    org.hibernate.SQL: debug

# ?????
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers
  info:
    env:
      enabled: true
