apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    uid: prom_ds_uid
    isDefault: true
    editable: true
    jsonData:
      manageAlerts: true