spring:
  application:
    name: ozang-batch
  profiles:
    include: core
    active: dev

  cache:
    type: redis
    redis:
      cache-null-values: false
      key-prefix: "ozang:"
      use-key-prefix: true
      enable-statistics: true

  # Spring Batch 기본 설정
  batch:
    job:
      enabled: false #애플리케이션 시작 시 배치 작업 자동 실행 여부
    jdbc:
      initialize-schema: never #배치 메타데이터 테이블 초기화

logging:
  level:
    root: INFO
    com.fourthread.ozang: DEBUG
    org.springframework.web: DEBUG
    org.springframework.batch: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.elasticsearch.client: trace

weather:
  cache:
    current:
      ttl: PT1H  # 현재 날씨 캐시 TTL (1시간)
    forecast:
      ttl: PT3H  # 5일 예보 캐시 TTL (3시간)
    location:
      ttl: PT24H # 위치 정보 캐시 TTL (24시간)

  api:
    key:  ${WEATHER_API_KEY}
    base-url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
    nowcast:
      url: ${weather.api.base-url}/getUltraSrtNcst
    forecast:
      url: ${weather.api.base-url}/getVilageFst

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: https://dapi.kakao.com

app:
  timezone: Asia/Seoul

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator

server:
  tomcat:
    port: 8081
    mbeanregistry:
      enabled: true