plugins {
    id 'org.springframework.boot' version '3.5.3'
    id 'io.spring.dependency-management' version '1.1.7'
}
group = 'com.ozang'
version = rootProject.version

dependencies {
    implementation project(':ozang-common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
    implementation 'software.amazon.awssdk:s3:2.31.14'
    implementation 'software.amazon.awssdk:protocol-core:2.31.14'
    implementation 'software.amazon.awssdk:s3-transfer-manager:2.31.14'
    implementation 'software.amazon.awssdk.crt:aws-crt:0.34.1'
    implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-impl:0.11.5'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.11.5'
    implementation 'com.nimbusds:nimbus-jose-jwt:10.3'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'org.springframework.retry:spring-retry'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'com.openai:openai-java:2.14.0'
    implementation 'me.paulschwarz:spring-dotenv:4.0.0'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    // 필요시 swagger, webflux 등 추가
}
