version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: do-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:11.1.0
    container_name: do-grafana
    user: root
    ports:
      - "9900:3000"
    volumes:
      - ./conf/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./conf/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./conf/grafana/dashboards:/var/lib/grafana/dashboards
      - ./data/grafana:/var/lib/grafana
    restart: unless-stopped