name: Test Coverage

on:
  push:
    branches: [ main, develop, 'release*' ]
  pull_request:
    branches: [ main, develop, 'release*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      TZ: Asia/Seoul
      JAVA_OPTS: -Duser.timezone=Asia/Seoul
      KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set timezone to KST
        run: |
          sudo timedatectl set-timezone Asia/Seoul
          echo "Current time: $(date)"
          echo "Java timezone will be set to: Asia/Seoul"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Verify timezone and run tests with JaCoCo
        run: |
          echo "=== Timezone Verification ==="
          echo "System timezone: $(timedatectl show --property=Timezone --value)"
          echo "Current date/time: $(date)"
          echo "Java timezone: $JAVA_OPTS"
          echo "=========================="
          echo "Starting tests with JaCoCo coverage..."
          ./gradlew clean test jacocoTestReport
        env:
          TZ: Asia/Seoul
          JAVA_TOOL_OPTIONS: -Duser.timezone=Asia/Seoul

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            ./build/reports/tests/
            ./build/reports/jacoco/
            ./build/reports/problems/
          retention-days: 7
          include-hidden-files: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FourThread/sb01-otboo-team01
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: false
          verbose: true