name: Test Coverage

on:
  push:
    branches: [ main, develop, 'release*' ]
  pull_request:
    branches: [ main, develop, 'release*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with JaCoCo
        run: |
          ./gradlew clean test jacocoTestReport

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4

        with:
          name: test-reports
          path: |
            ./build/reports/tests/
            ./build/reports/jacoco/
            ./build/reports/problems/
          retention-days: 7
          include-hidden-files: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FourThread/sb01-otboo-team01
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: false
          verbose: true
